/* This file is for later merging with install.mysql.uft8.sql */
/* It has been applied to the testing server ID264608 */
/*Table structure for table `#__jed_email_templates` */

DROP TABLE IF EXISTS `#__jed_email_templates`;

CREATE TABLE `#__jed_email_templates` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `subject` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `template` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_type` tinyint NOT NULL DEFAULT '0',
  `created_by` int NOT NULL DEFAULT '0',
  `modified_by` int NOT NULL DEFAULT '0',
  `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `state` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `#__jed_email_templates` */

insert  into `#__jed_email_templates`(`id`,`title`,`subject`,`template`,`email_type`,`created_by`,`modified_by`,`created`,`modified`,`state`) values (1,'Notification of Report','Dummy Subject','<p>Dear Developer I am writing to you to know that a report has been made to Joomla! regarding your extension Please investigate and report back to us using this link Best Wishes The Joomla Extension Directory Team</p>',2,769,652,'2021-02-10 12:09:44','2021-05-24 23:44:08',1);
insert  into `#__jed_email_templates`(`id`,`title`,`subject`,`template`,`email_type`,`created_by`,`modified_by`,`created`,`modified`,`state`) values (2,'Review Report Received','Review Report Received','<p>Your report has been successfully received and a ticket has been opened. A team member will look into the issue and you should receive an update to your ticket within the next 3 business days.</p>',1,652,652,'2021-05-13 14:37:13','2021-05-13 14:37:13',1);
insert  into `#__jed_email_templates`(`id`,`title`,`subject`,`template`,`email_type`,`created_by`,`modified_by`,`created`,`modified`,`state`) values (3,'Listing Submission Received','Listing Submission Received','<p>Your submission has been successfully received.</p>\r\n<p>Your listing will be screened by an extension specialist. If it passes all of our requirements it will be published. If it does not pass the initial screening you will receive a notice outlining the errors found and the next steps to take. If you checked the field \"My extension includes external libraries\" it will be manually screened in the order it was received by a team member.</p>\r\n<p><strong>NOTE</strong>: Our extension specialists review the extensions with <strong>JED Checker</strong>.&nbsp;The JED checker can be used to identify which files have issues - <a href=\"http://extensions.joomla.org/extension/jedchecker\" rel=\"alternate\">http://extensions.joomla.org/extension/jedchecker</a>.&nbsp;<strong>You are still on time to do a last check up</strong>.</p>\r\n<hr />\r\n<h2>Support the Joomla Community. Sponsor Us!</h2>\r\n<p><a href=\"https://community.joomla.org/sponsorship-campaigns.html\"><img src=\"https://extensions.joomla.org/images/social-images/joomla-community-sponsorships.jpg\" alt=\"Sponsor Us!\" /></a></p>\r\n<p><a href=\"https://community.joomla.org/sponsorship-campaigns.html\" target=\"_blank\" rel=\"noopener noreferrer\"><strong>Community Sponsorships</strong></a> allow those looking to support the project with smaller sponsorship amounts. With community sponsorships available from $5, every little bit helps to make Joomla! better.</p>\r\n<p><a class=\"btn btn-primary\" href=\"https://community.joomla.org/community-2017.html\" target=\"_blank\" rel=\"noopener noreferrer\"> Sponsor Now! </a></p>\r\n<hr />\r\n<ul>\r\n<li><a href=\"http://extensions.joomla.org/index.php?option=com_jed&amp;view=extension&amp;layout=edit&amp;amp;id={fab_qs}extension_id{/fab_qs}\">Back to edit {fab_qs}core_title{/fab_qs}</a></li>\r\n<li><a href=\"http://extensions.joomla.org/browse/my-extensions\">View my listings</a></li>\r\n</ul>',1,652,652,'2021-05-13 14:37:13','2021-05-13 14:37:13',1);
insert  into `#__jed_email_templates`(`id`,`title`,`subject`,`template`,`email_type`,`created_by`,`modified_by`,`created`,`modified`,`state`) values (4,'Listing Update Received','Listing Update Received','<p>Your extension&nbsp;has been successfully updated.</p>\r\n<hr />\r\n<h2>Support the Joomla Community. Sponsor Us!</h2>\r\n<p><a href=\"https://community.joomla.org/sponsorship-campaigns.html\"><img src=\"https://extensions.joomla.org/images/social-images/joomla-community-sponsorships.jpg\" alt=\"Sponsor Us!\" /></a></p>\r\n<p><a href=\"https://community.joomla.org/sponsorship-campaigns.html\" target=\"_blank\" rel=\"noopener noreferrer\"><strong>Community Sponsorships</strong></a> allow those looking to support the project with smaller sponsorship amounts. With community sponsorships available from $5, every little bit helps to make Joomla! better.</p>\r\n<p><a class=\"btn btn-primary\" href=\"https://community.joomla.org/community-2017.html\" target=\"_blank\" rel=\"noopener noreferrer\"> Sponsor Now! </a></p>\r\n<hr />\r\n<p><a class=\"btn btn-info\" href=\"https://extensions.joomla.org/index.php?option=com_jed&amp;view=extension&amp;layout=edit&amp;amp;id={fab_qs}extension_id{/fab_qs}&amp;Itemid=134\">Back to edit {fab_qs}core_title{/fab_qs}</a> <a class=\"btn btn-primary\" href=\"https://extensions.joomla.org/index.php?option=com_jed&amp;view=extension&amp;layout=default&amp;id={fab_qs}extension_id{/fab_qs}&amp;Itemid=145\">Continue to {fab_qs}core_title{/fab_qs}</a> <a class=\"btn\" href=\"https://extensions.joomla.org/browse/my-extensions\">View my listings</a></p>',1,652,652,'2021-05-13 14:37:13','2021-05-13 14:37:13',1);
insert  into `#__jed_email_templates`(`id`,`title`,`subject`,`template`,`email_type`,`created_by`,`modified_by`,`created`,`modified`,`state`) values (5,'Extension Report Received','Extension Report Received','<p>Your report has been successfully received and a ticket has been opened. A team member will look into the issue and you should receive an update to your ticket within the next 3 business days.</p>',1,652,652,'2021-05-13 14:38:15','2021-05-13 14:38:15',1);
