SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS #__jed_admin_notes;
DROP TABLE IF EXISTS #__jed_audit;
DROP TABLE IF EXISTS #__jed_extension_files;
DROP TABLE IF EXISTS #__jed_extension_linkcheck_log;
DROP TABLE IF EXISTS #__jed_extensions;
DROP TABLE IF EXISTS #__jed_extensions_categories;
DROP TABLE IF EXISTS #__jed_extensions_favoured;
DROP TABLE IF EXISTS #__jed_extensions_files;
DROP TABLE IF EXISTS #__jed_extensions_images;
DROP TABLE IF EXISTS #__jed_extensions_joomla_versions;
DROP TABLE IF EXISTS #__jed_extensions_php_versions;
DROP TABLE IF EXISTS #__jed_extensions_published_reasons;
DROP TABLE IF EXISTS #__jed_extensions_related;
DROP TABLE IF EXISTS #__jed_extensions_status;
DROP TABLE IF EXISTS #__jed_extensions_types;
DROP TABLE IF EXISTS #__jed_hit_log;
DROP TABLE IF EXISTS #__jed_reviews;
DROP TABLE IF EXISTS #__jed_suspect_ip_range;
DROP TABLE IF EXISTS #__jed_ticket_files;
DROP TABLE IF EXISTS #__jed_tickets;
DROP TABLE IF EXISTS #__jed_user_bans;
DROP TABLE IF EXISTS #__jed_emails;
DROP TABLE IF EXISTS #__jed_email_logs;
DROP TABLE IF EXISTS #__jed_extensions_notes;
DROP TABLE IF EXISTS #__jed_extensions_approved_reasons;
SET FOREIGN_KEY_CHECKS=1;